name: Compile and release Mac agent

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: macos-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.13'

      - name: Compile
        run: |
          env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o ./rmmagent-macos-amd64
          env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o ./rmmagent-macos-arm64

      - name: Create universal binary
        run: |
          lipo -create ./rmmagent-macos-amd64 ./rmmagent-macos-arm64 -o ./rmmagent-macos

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./rmmagent-macos
          retention-days: 90