name: Compile and release Mac agent

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: macos-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.13'

      - name: Compile
        run: |
          env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o ./rmmagent-macos-amd64
          env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o ./rmmagent-macos-arm64

      - name: Create universal binary
        run: |
          lipo -create ./rmmagent-macos-amd64 ./rmmagent-macos-arm64 -o ./rmmagent-macos

      # Always upload artifacts for every build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rmmagent-macos
          path: |
            ./rmmagent-macos
            ./rmmagent-macos-amd64
            ./rmmagent-macos-arm64
          retention-days: 90

      # Create GitHub Release when a tag is pushed
      - name: Set Release version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Use workflow_dispatch version if provided
      - name: Set Release version from input
        if: github.event_name == 'workflow_dispatch'
        run: echo "RELEASE_VERSION=v${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          files: |
            ./rmmagent-macos
          name: Release ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          generate_release_notes: true